// VERSION: v1.4.1 クメン法修正版
window.compounds = [  
  { id: "benzene", name: "ベンゼン", formula: "C6H6", group: "基本物質", summary: "芳香族化合物の基本となる物質。ニトロ化、スルホン化、ハロゲン化、アルキル化などで多くの化合物へ進める。" },  
  { id: "nitrobenzene", name: "ニトロベンゼン", formula: "C6H5NO2", group: "ニトロ化合物", summary: "ベンゼンをニトロ化して得られる。還元するとアニリンになる。" },  
  { id: "aniline", name: "アニリン", formula: "C6H5NH2", group: "芳香族アミン", summary: "ニトロベンゼンの還元で得られる。塩基性を示し、アセチル化・ジアゾ化・臭素水との反応が重要。" },  
  { id: "anilinium_chloride", name: "アニリン塩酸塩", formula: "C6H5NH3Cl", group: "アニリンの塩", summary: "アニリンが塩酸と反応してできる塩。強塩基を加えるとアニリンを遊離する。" },  
  { id: "acetanilide", name: "アセトアニリド", formula: "C6H5NHCOCH3", group: "アミド", summary: "アニリンをアセチル化して得られる。アミノ基を保護した形として扱われることがある。" },  
  { id: "tribromoaniline", name: "2,4,6-トリブロモアニリン", formula: "C6H2Br3NH2", group: "アニリン誘導体", summary: "アニリンに臭素水を作用させると生じやすい。アミノ基がベンゼン環を活性化する。" },  
  { id: "diazonium", name: "ベンゼンジアゾニウム塩", formula: "C6H5N2+Cl-", group: "ジアゾニウム塩", summary: "アニリンのジアゾ化で得られる。フェノール、クロロベンゼン、ブロモベンゼン、アゾ化合物などへの変換に使う。" },  
  { id: "chlorobenzene", name: "クロロベンゼン", formula: "C6H5Cl", group: "ハロゲン化合物", summary: "ベンゼンの塩素化、またはジアゾニウム塩から得られる。高温高圧条件でフェノール系へ進める。" },  
  { id: "bromobenzene", name: "ブロモベンゼン", formula: "C6H5Br", group: "ハロゲン化合物", summary: "ベンゼンの臭素化、またはジアゾニウム塩から得られる。" },  
  { id: "benzenesulfonic_acid", name: "ベンゼンスルホン酸", formula: "C6H5SO3H", group: "スルホン酸", summary: "ベンゼンのスルホン化で得られる。アルカリ融解でナトリウムフェノキシドに進める。" },  
  { id: "sodium_phenoxide", name: "ナトリウムフェノキシド", formula: "C6H5ONa", group: "フェノール塩", summary: "フェノールが塩基と反応してできる塩。酸性化するとフェノールに戻る。" },  
  { id: "phenol", name: "フェノール", formula: "C6H5OH", group: "フェノール類", summary: "弱酸性を示す芳香族化合物。臭素水、塩化鉄(III)、コルベ・シュミット反応、アセチル化などが重要。" },  
  { id: "phenyl_acetate", name: "酢酸フェニル", formula: "CH3COOC6H5", group: "エステル", summary: "フェノールをアセチル化して得られるエステル。" },  
  { id: "tribromophenol", name: "2,4,6-トリブロモフェノール", formula: "C6H2Br3OH", group: "フェノール誘導体", summary: "フェノールに臭素水を作用させると得られやすい。白色沈殿として扱われる。" },  
  { id: "o_nitrophenol", name: "o-ニトロフェノール", formula: "o-HOC6H4NO2", group: "ニトロフェノール", summary: "フェノールのニトロ化で生じる異性体の一つ。" },  
  { id: "p_nitrophenol", name: "p-ニトロフェノール", formula: "p-HOC6H4NO2", group: "ニトロフェノール", summary: "フェノールのニトロ化で生じる異性体の一つ。" },  
  { id: "picric_acid", name: "ピクリン酸", formula: "2,4,6-(NO2)3C6H2OH", group: "ニトロフェノール", summary: "2,4,6-トリニトロフェノール。フェノールの強いニトロ化で扱われることがある。" },  
  { id: "salicylic_acid", name: "サリチル酸", formula: "o-HOC6H4COOH", group: "ヒドロキシカルボン酸", summary: "フェノールからコルベ・シュミット反応で得られる。フェノール性ヒドロキシ基とカルボキシ基の両方をもつ。" },  
  { id: "sodium_salicylate", name: "サリチル酸ナトリウム", formula: "o-HOC6H4COONa", group: "カルボン酸塩", summary: "サリチル酸のカルボキシ基が塩になった物質。酸性化でサリチル酸に戻る。" },  
  { id: "acetylsalicylic_acid", name: "アセチルサリチル酸", formula: "C9H8O4", group: "エステル", summary: "サリチル酸をアセチル化して得られる。サリチル酸のフェノール性ヒドロキシ基が反応する。" },  
  { id: "methyl_salicylate", name: "サリチル酸メチル", formula: "HOC6H4COOCH3", group: "エステル", summary: "サリチル酸とメタノールのエステル化で得られる。" },  
  { id: "toluene", name: "トルエン", formula: "C6H5CH3", group: "芳香族炭化水素", summary: "ベンゼン環にメチル基がついた物質。側鎖の酸化と側鎖の塩素化が重要。" },  
  { id: "benzyl_chloride", name: "ベンジルクロリド", formula: "C6H5CH2Cl", group: "側鎖ハロゲン化物", summary: "トルエンの側鎖塩素化で得られる。加水分解でベンジルアルコールになる。" },  
  { id: "benzyl_alcohol", name: "ベンジルアルコール", formula: "C6H5CH2OH", group: "アルコール", summary: "ベンジルクロリドの加水分解で得られる。酸化でベンズアルデヒドになる。" },  
  { id: "benzaldehyde", name: "ベンズアルデヒド", formula: "C6H5CHO", group: "アルデヒド", summary: "ベンジルアルコールの酸化で得られる。さらに酸化すると安息香酸になる。銀鏡反応は陽性として扱う。" },  
  { id: "benzoic_acid", name: "安息香酸", formula: "C6H5COOH", group: "芳香族カルボン酸", summary: "トルエンの側鎖酸化などで得られる。炭酸水素ナトリウムと反応して二酸化炭素を発生する。" },  
  { id: "sodium_benzoate", name: "安息香酸ナトリウム", formula: "C6H5COONa", group: "カルボン酸塩", summary: "安息香酸と塩基の反応で得られる塩。酸性化で安息香酸に戻る。" },  
  { id: "methyl_benzoate", name: "安息香酸メチル", formula: "C6H5COOCH3", group: "エステル", summary: "安息香酸とメタノールのエステル化で得られる。加水分解で安息香酸系へ戻る。" },  
  { id: "o_xylene", name: "o-キシレン", formula: "o-C6H4(CH3)2", group: "芳香族炭化水素", summary: "メチル基が隣り合ったキシレン。酸化でフタル酸になる。" },  
  { id: "p_xylene", name: "p-キシレン", formula: "p-C6H4(CH3)2", group: "芳香族炭化水素", summary: "メチル基が向かい合ったキシレン。酸化でテレフタル酸になる。" },  
  { id: "phthalic_acid", name: "フタル酸", formula: "o-C6H4(COOH)2", group: "芳香族ジカルボン酸", summary: "o-キシレンの酸化で得られる。" },  
  { id: "terephthalic_acid", name: "テレフタル酸", formula: "p-C6H4(COOH)2", group: "芳香族ジカルボン酸", summary: "p-キシレンの酸化で得られる。PETにつながる物質として重要。" },  
  { id: "cumene", name: "クメン", formula: "C6H5CH(CH3)2", group: "芳香族炭化水素", summary: "ベンゼンにプロピレンを付加して得られる。クメン法でフェノールとアセトンの原料になる。" },  
  { id: "acetone", name: "アセトン", formula: "CH3COCH3", group: "ケトン", summary: "クメン法でフェノールとともに生じる。芳香族化合物ではないが、生成物として出る。" },  
  { id: "azo_phenol", name: "p-ヒドロキシアゾベンゼン", formula: "C6H5N=NC6H4OH", group: "アゾ化合物", summary: "ジアゾニウム塩とフェノールのカップリングで生じる代表的なアゾ化合物。" },  
  { id: "azo_aniline", name: "p-アミノアゾベンゼン", formula: "C6H5N=NC6H4NH2", group: "アゾ化合物", summary: "ジアゾニウム塩とアニリンのカップリングで生じる代表的なアゾ化合物。" },
  { id: "acetophenone", name: "アセトフェノン", formula: "C6H5COCH3", group: "芳香族ケトン", summary: "ベンゼン環にアセチル基 COCH3 がついた芳香族ケトン。ベンゼンのFriedel-Craftsアシル化で得られる。" },
  { id: "cyclohexane", name: "シクロヘキサン", formula: "C6H12", group: "シクロアルカン", summary: "ベンゼンに水素を付加して得られる飽和環状炭化水素。芳香族性はない。" },
  { id: "benzene_hexachloride", name: "ベンゼンヘキサクロリド", formula: "C6H6Cl6", group: "塩素付加物", summary: "別名：1,2,3,4,5,6-ヘキサクロロシクロヘキサン。ベンゼンに塩素が付加して得られる化合物。芳香族性は失われる。" },
  { id: "cumene_hydroperoxide", name: "クメンヒドロペルオキシド", formula: "C6H5C(CH3)2OOH", group: "ヒドロペルオキシド", summary: "クメンを酸素で酸化して得られるクメン法の中間体。酸分解によりフェノールとアセトンを生じる。" },
  { id: "m_xylene", name: "m-キシレン", formula: "m-C6H4(CH3)2", group: "芳香族炭化水素", summary: "メチル基がメタ位にあるキシレン。酸化でイソフタル酸になる。" },
  { id: "isophthalic_acid", name: "イソフタル酸", formula: "m-C6H4(COOH)2", group: "芳香族ジカルボン酸", summary: "m-キシレンの酸化で得られる芳香族ジカルボン酸。" }
];  
  
window.reactions = [  
  { from: "benzene", to: "nitrobenzene", type: "置換", name: "ニトロ化", reagent: "濃硝酸 + 濃硫酸", point: "ベンゼン環のHが -NO2 に置き換わる。", exam: "ベンゼンからアニリンへ進む最初の反応として重要。" },  
  { from: "nitrobenzene", to: "aniline", type: "還元", name: "ニトロ基の還元", reagent: "Sn + 塩酸 など", point: "-NO2 が -NH2 に変わる。", exam: "ニトロベンゼン → アニリンは頻出。" },  
  { from: "aniline", to: "anilinium_chloride", type: "酸塩基", name: "塩酸との反応", reagent: "塩酸", point: "アニリンは弱塩基なので、塩酸と反応して塩を作る。", exam: "アニリンが塩基性を示すことの確認。" },  
  { from: "anilinium_chloride", to: "aniline", type: "酸塩基", name: "アニリンの遊離", reagent: "NaOH などの強塩基", point: "アニリン塩酸塩に強塩基を加えるとアニリンが遊離する。", exam: "有機塩基の分離問題で出やすい。" },  
  { from: "aniline", to: "acetanilide", type: "アセチル化", name: "アミノ基のアセチル化", reagent: "無水酢酸 など", point: "-NH2 が -NHCOCH3 になる。", exam: "アニリンの反応性を調整する流れで出やすい。" },  
  { from: "aniline", to: "tribromoaniline", type: "置換", name: "臭素水との反応", reagent: "臭素水", point: "アミノ基によりベンゼン環が活性化し、2,4,6-置換体ができやすい。", exam: "フェノールの臭素水反応とセットで覚える。" },  
  { from: "aniline", to: "diazonium", type: "置換", name: "ジアゾ化", reagent: "亜硝酸ナトリウム + 塩酸、低温", point: "-NH2 からジアゾニウム塩を作る。", exam: "芳香族で別の置換基へ変える中継地点。" },  
  { from: "diazonium", to: "phenol", type: "置換", name: "加水分解", reagent: "水、加熱", point: "ジアゾニウム基が -OH に置き換わる。", exam: "アニリンからフェノールへ行く重要ルート。" },  
  { from: "diazonium", to: "chlorobenzene", type: "置換", name: "クロロ化", reagent: "塩化銅(I) など", point: "ジアゾニウム基が -Cl に置き換わる。", exam: "ジアゾニウム塩からハロゲン化ベンゼンを作る。" },  
  { from: "diazonium", to: "bromobenzene", type: "置換", name: "ブロモ化", reagent: "臭化銅(I) など", point: "ジアゾニウム基が -Br に置き換わる。", exam: "ジアゾニウム塩の変換先として整理する。" },  
  { from: "diazonium", to: "benzene", type: "還元", name: "水素への置換", reagent: "還元剤", point: "ジアゾニウム基が H に置き換わる。", exam: "置換基を外す方向の反応として扱える。" },  
  { from: "diazonium", to: "azo_phenol", type: "ジアゾカップリング", name: "フェノールとのカップリング", reagent: "フェノール、弱塩基性", point: "ジアゾニウム塩とフェノールが反応してアゾ化合物を作る。", exam: "染料・アゾ化合物の生成として問われることがある。" },  
  { from: "diazonium", to: "azo_aniline", type: "ジアゾカップリング", name: "アニリンとのカップリング", reagent: "アニリン、弱酸性〜中性", point: "ジアゾニウム塩とアニリンが反応してアゾ化合物を作る。", exam: "アゾ染料の生成ルートとして整理する。" },  
  { from: "benzene", to: "chlorobenzene", type: "置換", name: "塩素化", reagent: "Cl2 + FeCl3", point: "ベンゼン環のHが -Cl に置き換わる。", exam: "Cl2 + FeCl3 は環への置換。Cl2 + 光とは区別。" },  
  { from: "benzene", to: "bromobenzene", type: "置換", name: "臭素化", reagent: "Br2 + FeBr3", point: "ベンゼン環のHが -Br に置き換わる。", exam: "塩素化とセットで覚える。" },  
  { from: "benzene", to: "benzenesulfonic_acid", type: "置換", name: "スルホン化", reagent: "濃硫酸 または 発煙硫酸", point: "ベンゼン環に -SO3H が入る。", exam: "フェノールを作る別ルートにつながる。" },  
  { from: "benzenesulfonic_acid", to: "sodium_phenoxide", type: "置換", name: "アルカリ融解", reagent: "NaOH、高温", point: "-SO3Na 由来の部分が -ONa に変わる。", exam: "ベンゼンスルホン酸 → フェノールの中間段階。" },  
  { from: "sodium_phenoxide", to: "phenol", type: "酸塩基", name: "酸性化", reagent: "酸を加える", point: "C6H5O- が H+ を受け取りフェノールになる。", exam: "塩から弱酸を遊離させる流れ。" },  
  { from: "phenol", to: "sodium_phenoxide", type: "酸塩基", name: "中和", reagent: "NaOH", point: "フェノールは弱酸性なので、強塩基と反応して塩を作る。", exam: "アルコールとの違いを問われやすい。" },  
  { from: "phenol", to: "sodium_phenoxide", type: "酸塩基", name: "ナトリウムとの反応", reagent: "Na", point: "フェノールがナトリウムフェノキシドになり、水素が発生する。", exam: "フェノール性ヒドロキシ基の酸性を確認する反応。" },  
  { from: "phenol", result: "紫色を呈する", type: "確認反応", name: "塩化鉄(III)水溶液との反応", reagent: "FeCl3水溶液", point: "フェノール性ヒドロキシ基をもつ化合物は呈色することがある。", exam: "フェノール類の確認反応として重要。" },  
  { from: "chlorobenzene", to: "sodium_phenoxide", type: "置換", name: "高温高圧での置換", reagent: "NaOH、高温・高圧", point: "クロロベンゼンからフェノキシドへ進む。", exam: "クロロベンゼン → フェノール系の工業的ルート。" },  
  { from: "phenol", to: "tribromophenol", type: "置換", name: "臭素水との反応", reagent: "臭素水", point: "2,4,6-トリブロモフェノールができやすい。", exam: "白色沈殿として確認反応で出やすい。" },  
  { from: "phenol", to: "salicylic_acid", type: "置換", name: "コルベ・シュミット反応", reagent: "CO2、NaOH、加圧後に酸性化", point: "フェノールのオルト位に -COOH が入る。", exam: "フェノール → サリチル酸の最重要ルート。" },  
  { from: "phenol", to: "phenyl_acetate", type: "アセチル化", name: "フェノールのアセチル化", reagent: "無水酢酸 など", point: "フェノール性ヒドロキシ基がアセチル化され、酢酸フェニルになる。", exam: "サリチル酸のアセチル化と比較して整理する。" },  
  { from: "phenol", to: "o_nitrophenol", type: "置換", name: "ニトロ化", reagent: "希硝酸", point: "フェノールのオルト位・パラ位にニトロ基が入りやすい。", exam: "フェノールはベンゼンより置換反応を受けやすい。" },  
  { from: "phenol", to: "p_nitrophenol", type: "置換", name: "ニトロ化", reagent: "希硝酸", point: "フェノールのオルト位・パラ位にニトロ基が入りやすい。", exam: "配向性の理解に使える。" },  
  { from: "phenol", to: "picric_acid", type: "置換", name: "強いニトロ化", reagent: "濃硝酸 など", point: "2,4,6-トリニトロフェノールが生じる。", exam: "フェノールの反応性が高いことを示す例。" },  
  { from: "salicylic_acid", result: "紫色を呈する", type: "確認反応", name: "塩化鉄(III)水溶液との反応", reagent: "FeCl3水溶液", point: "サリチル酸にはフェノール性ヒドロキシ基があるため呈色する。", exam: "サリチル酸とアセチルサリチル酸の識別で出ることがある。" },  
  { from: "salicylic_acid", to: "sodium_salicylate", type: "酸塩基", name: "炭酸水素ナトリウムとの反応", reagent: "NaHCO3", point: "カルボキシ基が反応して塩となり、CO2が発生する。", exam: "フェノール単独ではNaHCO3と反応しにくい点と比較。" },  
  { from: "sodium_salicylate", to: "salicylic_acid", type: "酸塩基", name: "酸性化", reagent: "塩酸など", point: "サリチル酸ナトリウムに酸を加えるとサリチル酸が遊離する。", exam: "カルボン酸塩からカルボン酸を取り出す流れ。" },  
  { from: "salicylic_acid", to: "acetylsalicylic_acid", type: "アセチル化", name: "アセチル化", reagent: "無水酢酸 など", point: "フェノール性ヒドロキシ基がアセチル化される。", exam: "サリチル酸 → アセチルサリチル酸は頻出。" },  
  { from: "salicylic_acid", to: "methyl_salicylate", type: "エステル化", name: "エステル化", reagent: "メタノール + 濃硫酸", point: "カルボキシ基がメチルエステルになる。", exam: "サリチル酸の -COOH 側が反応する。" },  
  { from: "methyl_salicylate", to: "sodium_salicylate", type: "加水分解", name: "エステルのけん化", reagent: "NaOH水溶液、加熱", point: "エステルが加水分解され、カルボン酸塩とアルコールを生じる。", exam: "エステル化の逆向きとして整理する。" },  
  { from: "acetylsalicylic_acid", to: "salicylic_acid", type: "加水分解", name: "エステル結合の加水分解", reagent: "酸または塩基、水、加熱", point: "アセチル基が外れてサリチル酸側へ戻る。", exam: "アセチルサリチル酸がエステルであることの確認。" },  
  { from: "benzene", to: "toluene", type: "置換", name: "アルキル化", reagent: "CH3Cl + AlCl3 など", point: "ベンゼン環に -CH3 が入る。", exam: "トルエンから安息香酸へつながる出発点。" },  
  { from: "benzene", to: "cumene", type: "置換", name: "クメンの生成", reagent: "プロピレン、酸触媒", point: "ベンゼンにイソプロピル基を導入する。", exam: "クメン法の出発物質として問われることがある。" },  
  { from: "toluene", to: "benzoic_acid", type: "酸化", name: "側鎖の酸化", reagent: "KMnO4 など", point: "メチル基が -COOH まで酸化される。", exam: "トルエン → 安息香酸は超頻出。" },  
  { from: "toluene", to: "benzyl_chloride", type: "置換", name: "側鎖の塩素化", reagent: "Cl2、光", point: "ベンゼン環ではなく側鎖のHが置換される。", exam: "Cl2 + 光なら側鎖、Cl2 + FeCl3なら環への置換。" },  
  { from: "benzyl_chloride", to: "benzyl_alcohol", type: "加水分解", name: "加水分解", reagent: "NaOH水溶液 など", point: "-CH2Cl が -CH2OH に変わる。", exam: "側鎖ハロゲン化物からアルコールへ。" },  
  { from: "benzyl_alcohol", to: "benzaldehyde", type: "酸化", name: "穏やかな酸化", reagent: "酸化剤", point: "第一級アルコールがアルデヒドになる。", exam: "さらに酸化すると安息香酸へ進む。" },  
  { from: "benzaldehyde", to: "benzoic_acid", type: "酸化", name: "アルデヒドの酸化", reagent: "酸化剤", point: "-CHO が -COOH に変わる。", exam: "ベンズアルデヒド → 安息香酸。" },  
  { from: "benzaldehyde", result: "銀鏡反応：陽性", type: "確認反応", name: "銀鏡反応", reagent: "アンモニア性硝酸銀水溶液", point: "アルデヒド基をもつため、銀鏡反応を示す。", exam: "ベンズアルデヒドの確認反応として重要。" },  
  { from: "benzaldehyde", result: "フェーリング液：基本的に陰性扱い", type: "確認反応", name: "フェーリング液との反応", reagent: "フェーリング液", point: "芳香族アルデヒドはフェーリング液を還元しにくいものとして扱われる。", exam: "脂肪族アルデヒドとの違いとして出ることがある。" },  
  { from: "benzoic_acid", to: "sodium_benzoate", type: "酸塩基", name: "水酸化ナトリウムとの反応", reagent: "NaOH", point: "カルボン酸が中和されてカルボン酸塩になる。", exam: "安息香酸の酸性を確認する反応。" },  
  { from: "benzoic_acid", to: "sodium_benzoate", type: "酸塩基", name: "炭酸水素ナトリウムとの反応", reagent: "NaHCO3", point: "安息香酸が塩になり、CO2が発生する。", exam: "フェノールとの分離・識別で重要。" },  
  { from: "sodium_benzoate", to: "benzoic_acid", type: "酸塩基", name: "酸性化", reagent: "塩酸など", point: "安息香酸ナトリウムに酸を加えると安息香酸が遊離する。", exam: "カルボン酸塩からカルボン酸を取り出す流れ。" },  
  { from: "benzoic_acid", to: "methyl_benzoate", type: "エステル化", name: "エステル化", reagent: "メタノール + 濃硫酸", point: "安息香酸のカルボキシ基がメチルエステルになる。", exam: "カルボン酸 + アルコール → エステル。" },  
  { from: "methyl_benzoate", to: "sodium_benzoate", type: "加水分解", name: "エステルのけん化", reagent: "NaOH水溶液、加熱", point: "安息香酸メチルが加水分解され、安息香酸ナトリウムとメタノールを生じる。", exam: "エステル化の逆向きとして重要。" },  
  { from: "o_xylene", to: "phthalic_acid", type: "酸化", name: "側鎖の酸化", reagent: "KMnO4 など", point: "2つのメチル基がそれぞれ -COOH まで酸化される。", exam: "o-キシレン → フタル酸。異性体対応を覚える。" },  
  { from: "p_xylene", to: "terephthalic_acid", type: "酸化", name: "側鎖の酸化", reagent: "KMnO4 など", point: "2つのメチル基がそれぞれ -COOH まで酸化される。", exam: "p-キシレン → テレフタル酸。PETとの関連でも出る。" },
  { from: "benzene", to: "acetophenone", type: "アシル化", name: "Friedel-Crafts アシル化", reagent: "CH3COCl + AlCl3", point: "ベンゼン環のHがアシル基 COCH3 に置き換わる。", exam: "アルキル化とセットで、ベンゼン環への置換反応として整理する。" },
  { from: "benzene", to: "cyclohexane", type: "付加", name: "水素付加", reagent: "H2、Niなどの触媒、高温・高圧", point: "ベンゼン環に水素が付加して、シクロヘキサンになる。", exam: "ベンゼンの通常反応は置換が中心だが、強い条件では付加反応も起こる。" },
  { from: "benzene", to: "benzene_hexachloride", type: "付加", name: "塩素付加", reagent: "Cl2、光", point: "ベンゼンに塩素が付加して、ベンゼンヘキサクロリドになる。", exam: "Cl2 + FeCl3 は置換、Cl2 + 光 は付加として区別する。" },
  { from: "cumene", to: "cumene_hydroperoxide", type: "酸化", name: "クメンの酸化", reagent: "O2", point: "クメンの側鎖が酸化され、クメンヒドロペルオキシドになる。", exam: "クメン法では、クメンを酸化してから酸分解する流れで整理する。" },
  { from: "cumene_hydroperoxide", to: "phenol", type: "酸分解", name: "クメンヒドロペルオキシドの酸分解", reagent: "酸", point: "クメンヒドロペルオキシドが酸分解してフェノールを生じる。", exam: "クメン法でフェノールが得られる段階。" },
  { from: "cumene_hydroperoxide", to: "acetone", type: "酸分解", name: "クメンヒドロペルオキシドの酸分解", reagent: "酸", point: "クメンヒドロペルオキシドが酸分解してアセトンも生じる。", exam: "クメン法ではフェノールとアセトンが同時に生じる。" },
  { from: "sodium_phenoxide", to: "sodium_salicylate", type: "置換", name: "コルベ・シュミット反応", reagent: "CO2、高温・高圧", point: "ナトリウムフェノキシドのオルト位にカルボキシ基が入り、サリチル酸ナトリウムになる。", exam: "フェノールからサリチル酸へ進むときの中間段階として重要。" },
  { from: "m_xylene", to: "isophthalic_acid", type: "酸化", name: "側鎖の酸化", reagent: "KMnO4 など", point: "2つのメチル基がそれぞれ -COOH まで酸化される。", exam: "m-キシレン → イソフタル酸。o, m, p の異性体対応を整理する。" },
  { from: "sodium_benzoate", to: "benzene", type: "脱炭酸", name: "ソーダ石灰による脱炭酸", reagent: "NaOH、CaO、加熱", point: "安息香酸ナトリウムからカルボキシ基が外れ、ベンゼンが生じる。", exam: "カルボン酸塩から炭化水素へ戻す反応として出ることがある。" },
  { from: "acetanilide", to: "aniline", type: "加水分解", name: "アセトアニリドの加水分解", reagent: "酸または塩基、水、加熱", point: "アセチル基が外れてアニリン側へ戻る。", exam: "アニリンのアセチル化の逆反応として整理する。" },
  { from: "phenyl_acetate", to: "phenol", type: "加水分解", name: "酢酸フェニルの加水分解", reagent: "酸または塩基、水、加熱", point: "エステル結合が加水分解され、フェノール側へ戻る。", exam: "フェノールのアセチル化の逆反応として整理する。" },
  { from: "acetylsalicylic_acid", result: "FeCl3水溶液で基本的に呈色しにくい", type: "確認反応", name: "塩化鉄(III)水溶液との反応", reagent: "FeCl3水溶液", point: "アセチルサリチル酸ではフェノール性ヒドロキシ基がアセチル化されているため、サリチル酸のような紫色を示しにくい。", exam: "サリチル酸とアセチルサリチル酸の識別で重要。" }
];  